//! Stable semantic command IDs used by the keybinding runtime.

mod catalog;

pub use catalog::{RepeatPolicy, TerminalRequirement, command_spec};

/// A user-facing operation. IDs are intentionally independent of Rust enum
/// names so settings and diagnostics remain stable across refactors.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum CommandId {
    AppQuit,
    WorkspaceIdleEscape,
    TurnInterrupt,
    EditorSubmit,
    EditorNewline,
    EditorClear,
    EditorHistoryPrevious,
    EditorHistoryNext,
    EditorCursorLeft,
    EditorCursorRight,
    EditorCursorWordLeft,
    EditorCursorWordRight,
    EditorCursorLineStart,
    EditorCursorLineEnd,
    TextDeleteBackward,
    TextDeleteForward,
    TextDeleteWordBackward,
    TextDeleteWordForward,
    TextDeleteToLineStart,
    TextDeleteToLineEnd,
    TimelinePageUp,
    TimelinePageDown,
    TimelineUp,
    TimelineDown,
    TimelineJumpLatest,
    UiCancel,
    UiConfirm,
    SelectionPrevious,
    SelectionNext,
    SelectionPagePrevious,
    SelectionPageNext,
    CompletionAccept,
    CompletionAcceptAndSubmit,
    SessionListOpen,
    SessionTreeOpen,
    ModelSelectorOpen,
    AgentSelectorOpen,
    SettingsOpen,
    UsageOpen,
    NotificationDismissVisible,
    NotificationToggleScope,
    NotificationPrevious,
    NotificationNext,
    NotificationCopySelected,
    NotificationPageUp,
    NotificationPageDown,
    EditorFollowUp,
    EditorSteer,
    EditorDequeueFollowUp,
    ClipboardPasteImage,
    TreeFoldOrUp,
    TreeUnfoldOrDown,
    TreeEditLabel,
    TreeToggleLabelTimestamp,
    TreeFilterCycleForward,
    TreeFilterCycleBackward,
    SessionToggleScope,
    SessionToggleNamed,
    SessionTogglePath,
    ApprovalDecline,
    ApprovalConfirm,
    ApprovalPrevious,
    ApprovalNext,
    WorkflowSubmit,
    WorkflowCancel,
    WorkflowNextStep,
    WorkflowPreviousStep,
    WorkflowPreviousChoice,
    WorkflowNextChoice,
}

impl CommandId {
    pub const fn as_str(self) -> &'static str {
        use CommandId::*;
        match self {
            AppQuit => "app.quit",
            WorkspaceIdleEscape => "workspace.idleEscape",
            TurnInterrupt => "turn.interrupt",
            EditorSubmit => "editor.submit",
            EditorNewline => "editor.newline",
            EditorClear => "editor.clear",
            EditorHistoryPrevious => "editor.history.previous",
            EditorHistoryNext => "editor.history.next",
            EditorCursorLeft => "editor.cursor.left",
            EditorCursorRight => "editor.cursor.right",
            EditorCursorWordLeft => "editor.cursor.wordLeft",
            EditorCursorWordRight => "editor.cursor.wordRight",
            EditorCursorLineStart => "editor.cursor.lineStart",
            EditorCursorLineEnd => "editor.cursor.lineEnd",
            TextDeleteBackward => "text.deleteBackward",
            TextDeleteForward => "text.deleteForward",
            TextDeleteWordBackward => "text.deleteWordBackward",
            TextDeleteWordForward => "text.deleteWordForward",
            TextDeleteToLineStart => "text.deleteToLineStart",
            TextDeleteToLineEnd => "text.deleteToLineEnd",
            TimelinePageUp => "timeline.pageUp",
            TimelinePageDown => "timeline.pageDown",
            TimelineUp => "timeline.up",
            TimelineDown => "timeline.down",
            TimelineJumpLatest => "timeline.jumpLatest",
            UiCancel => "ui.cancel",
            UiConfirm => "ui.confirm",
            SelectionPrevious => "selection.previous",
            SelectionNext => "selection.next",
            SelectionPagePrevious => "selection.pagePrevious",
            SelectionPageNext => "selection.pageNext",
            CompletionAccept => "completion.accept",
            CompletionAcceptAndSubmit => "completion.acceptAndSubmit",
            SessionListOpen => "session.list.open",
            SessionTreeOpen => "session.tree.open",
            ModelSelectorOpen => "model.selector.open",
            AgentSelectorOpen => "agent.selector.open",
            SettingsOpen => "settings.open",
            UsageOpen => "usage.open",
            NotificationDismissVisible => "notification.dismissVisible",
            NotificationToggleScope => "notification.toggleScope",
            NotificationPrevious => "notification.previous",
            NotificationNext => "notification.next",
            NotificationCopySelected => "notification.copySelected",
            NotificationPageUp => "notification.pageUp",
            NotificationPageDown => "notification.pageDown",
            EditorFollowUp => "editor.followUp",
            EditorSteer => "editor.steer",
            EditorDequeueFollowUp => "editor.dequeueFollowUp",
            ClipboardPasteImage => "clipboard.pasteImage",
            TreeFoldOrUp => "tree.foldOrUp",
            TreeUnfoldOrDown => "tree.unfoldOrDown",
            TreeEditLabel => "tree.editLabel",
            TreeToggleLabelTimestamp => "tree.toggleLabelTimestamp",
            TreeFilterCycleForward => "tree.filterCycleForward",
            TreeFilterCycleBackward => "tree.filterCycleBackward",
            SessionToggleScope => "session.toggleScope",
            SessionToggleNamed => "session.toggleNamed",
            SessionTogglePath => "session.togglePath",
            ApprovalDecline => "approval.decline",
            ApprovalConfirm => "approval.confirm",
            ApprovalPrevious => "approval.previous",
            ApprovalNext => "approval.next",
            WorkflowSubmit => "workflow.submit",
            WorkflowCancel => "workflow.cancel",
            WorkflowNextStep => "workflow.nextStep",
            WorkflowPreviousStep => "workflow.previousStep",
            WorkflowPreviousChoice => "workflow.previousChoice",
            WorkflowNextChoice => "workflow.nextChoice",
        }
    }

    pub const ALL: &'static [Self] = &[
        Self::AppQuit,
        Self::WorkspaceIdleEscape,
        Self::TurnInterrupt,
        Self::EditorSubmit,
        Self::EditorNewline,
        Self::EditorClear,
        Self::EditorHistoryPrevious,
        Self::EditorHistoryNext,
        Self::EditorCursorLeft,
        Self::EditorCursorRight,
        Self::EditorCursorWordLeft,
        Self::EditorCursorWordRight,
        Self::EditorCursorLineStart,
        Self::EditorCursorLineEnd,
        Self::TextDeleteBackward,
        Self::TextDeleteForward,
        Self::TextDeleteWordBackward,
        Self::TextDeleteWordForward,
        Self::TextDeleteToLineStart,
        Self::TextDeleteToLineEnd,
        Self::TimelinePageUp,
        Self::TimelinePageDown,
        Self::TimelineUp,
        Self::TimelineDown,
        Self::TimelineJumpLatest,
        Self::UiCancel,
        Self::UiConfirm,
        Self::SelectionPrevious,
        Self::SelectionNext,
        Self::SelectionPagePrevious,
        Self::SelectionPageNext,
        Self::CompletionAccept,
        Self::CompletionAcceptAndSubmit,
        Self::SessionListOpen,
        Self::SessionTreeOpen,
        Self::ModelSelectorOpen,
        Self::AgentSelectorOpen,
        Self::SettingsOpen,
        Self::UsageOpen,
        Self::NotificationDismissVisible,
        Self::NotificationToggleScope,
        Self::NotificationPrevious,
        Self::NotificationNext,
        Self::NotificationCopySelected,
        Self::NotificationPageUp,
        Self::NotificationPageDown,
        Self::EditorFollowUp,
        Self::EditorSteer,
        Self::EditorDequeueFollowUp,
        Self::ClipboardPasteImage,
        Self::TreeFoldOrUp,
        Self::TreeUnfoldOrDown,
        Self::TreeEditLabel,
        Self::TreeToggleLabelTimestamp,
        Self::TreeFilterCycleForward,
        Self::TreeFilterCycleBackward,
        Self::SessionToggleScope,
        Self::SessionToggleNamed,
        Self::SessionTogglePath,
        Self::ApprovalDecline,
        Self::ApprovalConfirm,
        Self::ApprovalPrevious,
        Self::ApprovalNext,
        Self::WorkflowSubmit,
        Self::WorkflowCancel,
        Self::WorkflowNextStep,
        Self::WorkflowPreviousStep,
        Self::WorkflowPreviousChoice,
        Self::WorkflowNextChoice,
    ];

    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL
            .iter()
            .copied()
            .find(|command| command.as_str() == value.trim())
    }
}

impl std::fmt::Display for CommandId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
