use std::fmt::Write as _;

use crate::{CapacityPolicy, CommunicationSpec};

pub fn render_json(specs: &[CommunicationSpec]) -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(specs).map(|mut json| {
        json.push('\n');
        json
    })
}

pub fn render_mermaid(specs: &[CommunicationSpec]) -> String {
    let mut output = String::from(
        "# Generated Communication Topology\n\n> Generated by `piko-comms-topology`; do not edit manually.\n\n```mermaid\nflowchart LR\n",
    );
    let mut groups = std::collections::BTreeMap::<&str, Vec<&CommunicationSpec>>::new();
    let mut components = std::collections::BTreeSet::new();
    for spec in specs {
        let group = spec.id.split('.').next().unwrap_or("runtime");
        groups.entry(group).or_default().push(spec);
        components.extend(spec.producers.iter().copied());
        components.insert(spec.consumer);
    }
    for (group, entries) in groups {
        let _ = writeln!(output, "    subgraph {group}[\"{group}\"]");
        for spec in entries {
            let id = node_id(spec.id);
            let label = format!(
                "{}<br/>{:?} / {:?}<br/>{}",
                spec.id,
                spec.kind,
                spec.scope,
                capacity_label(spec.capacity)
            );
            let _ = writeln!(output, "        {id}[\"{label}\"]");
        }
        output.push_str("    end\n");
    }
    for component in components {
        let component_id = node_id(&format!("component_{component}"));
        let _ = writeln!(
            output,
            "    {component_id}[\"{}\"]",
            escape_label(component)
        );
    }
    for spec in specs {
        let id = node_id(spec.id);
        for producer in spec.producers {
            let producer_id = node_id(&format!("component_{producer}"));
            let _ = writeln!(output, "    {producer_id} --> {id}");
        }
        let consumer_id = node_id(&format!("component_{}", spec.consumer));
        let _ = writeln!(output, "    {id} --> {consumer_id}");
    }
    output.push_str("```\n");
    output
}

fn capacity_label(capacity: CapacityPolicy) -> String {
    match capacity {
        CapacityPolicy::Bounded(value) => format!("Bounded({value})"),
        CapacityPolicy::One => "One".into(),
        CapacityPolicy::Latest => "Latest".into(),
        CapacityPolicy::Unbounded { justification } => {
            format!("Unbounded — {}", escape_label(justification))
        }
    }
}

fn escape_label(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn node_id(value: &str) -> String {
    let mut result = String::with_capacity(value.len() + 2);
    result.push('n');
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            result.push(character);
        } else {
            result.push('_');
        }
    }
    result
}

#[cfg(test)]
mod tests {
    #[test]
    fn topology_is_deterministic() {
        let first = crate::render_mermaid(crate::ALL_SPECS);
        let second = crate::render_mermaid(crate::ALL_SPECS);
        assert_eq!(first, second);
        assert!(first.contains("orchd.agent.commands"));
    }
}
