//! History-specific default bindings.
use super::*;

pub(super) fn rules() -> Vec<BindingRule> {
    vec![
        rule!(
            "default-history-refresh",
            "r",
            HistoryRefresh,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-sessions",
            "s",
            HistoryChooseSession,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-filter",
            "/",
            HistoryFilter,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-detail-tab",
            "t",
            HistoryDetailTab,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-agent-next",
            "a",
            HistoryAgentNext,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-page-next",
            "tab",
            SelectionPageNext,
            History
        ),
        rule!(
            "default-history-page-prev",
            "shift+tab",
            SelectionPagePrevious,
            History
        ),
        rule!(
            "default-history-back",
            "backspace",
            UiCancel,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-left",
            "left",
            UiCancel,
            History,
            ["!text.inputActive"]
        ),
    ]
}
