//! History-specific default bindings.
use super::*;

pub(super) fn rules() -> Vec<BindingRule> {
    vec![
        rule!(
            "default-history-inspect",
            "i",
            HistoryInspect,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-refresh",
            "r",
            HistoryRefresh,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-sessions",
            "s",
            HistoryChooseSession,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-filter",
            "/",
            HistoryFilter,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-facts",
            "a",
            HistoryFactsOnly,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-diagnostics",
            "d",
            HistoryDiagnostics,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-lens-next",
            "tab",
            SelectionPageNext,
            History
        ),
        rule!(
            "default-history-lens-prev",
            "shift+tab",
            SelectionPagePrevious,
            History
        ),
        rule!(
            "default-history-back",
            "backspace",
            UiCancel,
            History,
            ["!text.inputActive"]
        ),
        rule!(
            "default-history-left",
            "left",
            UiCancel,
            History,
            ["!text.inputActive"]
        ),
    ]
}
